color: null
description: null
fieldLayouts:
  d3fde11e-d143-4eb3-8b83-b0380be37370:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-06T11:29:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e5e277a2-0bc2-4773-9e81-045ec709dfaa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e00544d6-043e-42cc-9823-ce289d260b8f
        userCondition: null
handle: sectionLandingPage2
hasTitleField: true
icon: null
name: 'Section Landing Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
