dateModified: 1765023097
email:
  fromEmail: martin@hypha.media
  fromName: 'Entry Level'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    8b0eb8fa-5a19-4e68-bd18-dcb0c249f224: 'Entry Level' # Entry Level
    5455e65b-99ce-4a1f-9b53-a78c08edd1fa: 'Section Landing Page' # Section Landing Page
    a3f07f14-f1ac-4845-b74f-ed0333754e26: 'A Level Three Entry' # A Level Three Entry
    b3461d75-57e6-4484-8e61-94098383e4fe: 'Structure Section One' # Structure Section One
    b9329609-fe03-4562-a9bd-030469642367: 'Section Landing Page' # Section Landing Page
    be036e7f-651b-41a0-a0b4-09fe4f0ffb68: 'Individual Article Page' # Individual Article Page
    c309933f-7fb2-44a5-997a-9f0646fbe7e8: 'Individual Article Page' # Individual Article Page
    f006d34c-9336-4dda-8070-3d78549608e5: 'Structure Section Two' # Structure Section Two
    fbbb1ae9-e077-4d51-bd76-766c9f985f46: 'Entry Level' # Entry Level
plugins:
  entry-level:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      sectionConfig:
        __assoc__:
          -
            - b3461d75-57e6-4484-8e61-94098383e4fe # Structure Section One
            -
              __assoc__:
                -
                  - typeHierarchy
                  -
                    __assoc__:
                      -
                        - b9329609-fe03-4562-a9bd-030469642367 # Section Landing Page
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - ''
                      -
                        - be036e7f-651b-41a0-a0b4-09fe4f0ffb68 # Individual Article Page
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - b9329609-fe03-4562-a9bd-030469642367 # Section Landing Page
                      -
                        - a3f07f14-f1ac-4845-b74f-ed0333754e26 # A Level Three Entry
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - be036e7f-651b-41a0-a0b4-09fe4f0ffb68 # Individual Article Page
                -
                  - typeOrder
                  -
                    - b9329609-fe03-4562-a9bd-030469642367 # Section Landing Page
                    - be036e7f-651b-41a0-a0b4-09fe4f0ffb68 # Individual Article Page
                    - a3f07f14-f1ac-4845-b74f-ed0333754e26 # A Level Three Entry
          -
            - f006d34c-9336-4dda-8070-3d78549608e5 # Structure Section Two
            -
              __assoc__:
                -
                  - typeHierarchy
                  -
                    __assoc__:
                      -
                        - 5455e65b-99ce-4a1f-9b53-a78c08edd1fa # Section Landing Page
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - ''
                      -
                        - c309933f-7fb2-44a5-997a-9f0646fbe7e8 # Individual Article Page
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - 5455e65b-99ce-4a1f-9b53-a78c08edd1fa # Section Landing Page
                -
                  - typeOrder
                  -
                    - 5455e65b-99ce-4a1f-9b53-a78c08edd1fa # Section Landing Page
                    - c309933f-7fb2-44a5-997a-9f0646fbe7e8 # Individual Article Page
system:
  edition: solo
  live: true
  name: 'Entry Level'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
