dateModified: 1764959562
email:
  fromEmail: martin@hypha.media
  fromName: 'Entry Level'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    8b0eb8fa-5a19-4e68-bd18-dcb0c249f224: 'Entry Level' # Entry Level
    27da2506-e958-41cf-a066-2be2fa0283d9: 'Entry Level Four' # Entry Level Four
    a3f07f14-f1ac-4845-b74f-ed0333754e26: 'Entry Level Three' # Entry Level Three
    b3461d75-57e6-4484-8e61-94098383e4fe: 'Entry Level' # Entry Level
    b9329609-fe03-4562-a9bd-030469642367: 'Entry Level One' # Entry Level One
    be036e7f-651b-41a0-a0b4-09fe4f0ffb68: 'Entry Level Two' # Entry Level Two
    fbbb1ae9-e077-4d51-bd76-766c9f985f46: 'Entry Level' # Entry Level
plugins:
  entry-types-defaults:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      sectionConfig:
        __assoc__:
          -
            - b3461d75-57e6-4484-8e61-94098383e4fe # Entry Level
            -
              __assoc__:
                -
                  - typeHierarchy
                  -
                    __assoc__:
                      -
                        - b9329609-fe03-4562-a9bd-030469642367 # Entry Level One
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - ''
                            -
                              - parentSelectionStrategy
                              - mostRecent
                            -
                              - specificParentId
                              - ''
                      -
                        - be036e7f-651b-41a0-a0b4-09fe4f0ffb68 # Entry Level Two
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - b9329609-fe03-4562-a9bd-030469642367 # Entry Level One
                            -
                              - parentSelectionStrategy
                              - mostRecent
                            -
                              - specificParentId
                              - ''
                      -
                        - a3f07f14-f1ac-4845-b74f-ed0333754e26 # Entry Level Three
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - be036e7f-651b-41a0-a0b4-09fe4f0ffb68 # Entry Level Two
                            -
                              - parentSelectionStrategy
                              - mostRecent
                            -
                              - specificParentId
                              - ''
                      -
                        - 27da2506-e958-41cf-a066-2be2fa0283d9 # Entry Level Four
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - a3f07f14-f1ac-4845-b74f-ed0333754e26 # Entry Level Three
                            -
                              - parentSelectionStrategy
                              - mostRecent
                            -
                              - specificParentId
                              - ''
system:
  edition: solo
  live: true
  name: 'Entry Level'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
